name: 'todo_io'
services:
    postgres:
        image: postgres:latest
        restart: always
        container_name: postgres
        environment:
          - POSTGRES_USER=root
          - POSTGRES_PASSWORD=password
        ports:
          - '5439:5432'
        volumes:
          - ./api/prisma/postgres-data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD", "pg_isready"]
            interval: 3s
            timeout: 5s
            retries: 5
