export const USER_EVENT = {
    REQUEST_JOIN: "USER:REQUEST:JOIN",
    JOINED: "USER:JOINED"
};

export const TODO_EVENT = {
    REQUEST_CREATE: "TODO:CREATE",
    CREATED: "TODO:CREATED",
    REQUEST_COMPLETE: "TODO:COMPLETE",
    COMPLETED: "TODO:COMPLETED"
};
